### PR TITLE
Merged pattern includes together for text.html.basic

### PR DESCRIPTION
**Pull request by brianhansonxyz**

### CODE REVIEW

**Comment by ExE-Boss** [comment]
Except that this would cause <code>tags&#x2011;valid</code>, <code>tags&#x2011;invalid</code> and&nbsp;`entities` to&nbsp;be&nbsp;loaded before EJS&nbsp;tags.

**Comment by Betanu701** [comment]
Taking the work from here, I have been working on loading html as the default language then load EJS then javascript. It is working about 80%. I do not see any issues with the highlighting but when I inspect the scopes, it seems like javascript block is taking precedence over ejs when there is nested blocks. 

`
<% for(var i = 0; i < 10; i++) { %>
<h1>Hi</h1>
<% if(i%2 == 0) { %>
<h2>foo</h2>
<% } %>
<h1>bye</h1>
<% } %>
` 

The second set of ejs tags is registering as javascript. Does not really cause issues with highlighting, just annoying that the scope is not being recognize correctly. I create a branch with my changes. I do not want to push it to prod yet.

**Comment by Betanu701** [comment]
See branch: top-level-html for updated code.

**Comment by brianhansonxyz** [comment]
Thank you for that insight, I didn't realize that the order of includes was relevant.

**Pull request closed without merging**
